//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrinksMachineProgram.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TextResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DrinksMachineProgram.Resources.TextResources", typeof(TextResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        public static string LabelPassword {
            get {
                return ResourceManager.GetString("LabelPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred while trying to add the record..
        /// </summary>
        public static string MessageErrorAddingRecord {
            get {
                return ResourceManager.GetString("MessageErrorAddingRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred while trying to delete the record..
        /// </summary>
        public static string MessageErrorDeletingRecord {
            get {
                return ResourceManager.GetString("MessageErrorDeletingRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Drink is sold out, your purchase cannot be processed..
        /// </summary>
        public static string MessageErrorDrinkSoldOut {
            get {
                return ResourceManager.GetString("MessageErrorDrinkSoldOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The user name or password are incorrect..
        /// </summary>
        public static string MessageErrorLoginIncorrect {
            get {
                return ResourceManager.GetString("MessageErrorLoginIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There was an error with the order..
        /// </summary>
        public static string MessageErrorOrder {
            get {
                return ResourceManager.GetString("MessageErrorOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The record does not exist..
        /// </summary>
        public static string MessageErrorRecordDoesNotExist {
            get {
                return ResourceManager.GetString("MessageErrorRecordDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred while trying to update the record..
        /// </summary>
        public static string MessageErrorUpdatingRecord {
            get {
                return ResourceManager.GetString("MessageErrorUpdatingRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The password must have at least 8 characters..
        /// </summary>
        public static string MessageErrorUserPasswordLength {
            get {
                return ResourceManager.GetString("MessageErrorUserPasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The password must have lowercase characters..
        /// </summary>
        public static string MessageErrorUserPasswordLowercases {
            get {
                return ResourceManager.GetString("MessageErrorUserPasswordLowercases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The password must have number characters..
        /// </summary>
        public static string MessageErrorUserPasswordNumbers {
            get {
                return ResourceManager.GetString("MessageErrorUserPasswordNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The password must have symbol characters..
        /// </summary>
        public static string MessageErrorUserPasswordSymbols {
            get {
                return ResourceManager.GetString("MessageErrorUserPasswordSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The password must have uppercase characters..
        /// </summary>
        public static string MessageErrorUserPasswordUppercases {
            get {
                return ResourceManager.GetString("MessageErrorUserPasswordUppercases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Not enough money to pay for drinks..
        /// </summary>
        public static string MessageNotEnoughMoney {
            get {
                return ResourceManager.GetString("MessageNotEnoughMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Not sufficient change in the inventory..
        /// </summary>
        public static string MessageNotSufficientChange {
            get {
                return ResourceManager.GetString("MessageNotSufficientChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Record added successfully..
        /// </summary>
        public static string MessageSucccessRecordAdded {
            get {
                return ResourceManager.GetString("MessageSucccessRecordAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Record updated successfully..
        /// </summary>
        public static string MessageSucccessRecordUpdated {
            get {
                return ResourceManager.GetString("MessageSucccessRecordUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a List generated..
        /// </summary>
        public static string MessageSuccessListGenerated {
            get {
                return ResourceManager.GetString("MessageSuccessListGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Order complete..
        /// </summary>
        public static string MessageSuccessOrder {
            get {
                return ResourceManager.GetString("MessageSuccessOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Record deleted successfully..
        /// </summary>
        public static string MessageSuccessRecordDeleted {
            get {
                return ResourceManager.GetString("MessageSuccessRecordDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CHANGE.
        /// </summary>
        public static string TitleChange {
            get {
                return ResourceManager.GetString("TitleChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a COINS INFORMATION.
        /// </summary>
        public static string TitleCoinsInformation {
            get {
                return ResourceManager.GetString("TitleCoinsInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Order Summary.
        /// </summary>
        public static string TitleOrderSummary {
            get {
                return ResourceManager.GetString("TitleOrderSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PRODUCTS INFORMATION.
        /// </summary>
        public static string TitleProductsInformation {
            get {
                return ResourceManager.GetString("TitleProductsInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PURCHASED PRODUCTS.
        /// </summary>
        public static string TitlePurchasedProducts {
            get {
                return ResourceManager.GetString("TitlePurchasedProducts", resourceCulture);
            }
        }
    }
}
